name: Scrape Changan Data

on:
  push:
    paths:
      - '.github/scripts/sh/scrape-changan.sh'
  workflow_call:
    outputs:
      changes:
        description: "Whether there were changes in the data"
        value: ${{ jobs.scrape.outputs.changes }}
      script_output:
        description: "Output message for notifications"
        value: ${{ jobs.scrape.outputs.script_output }}
  workflow_dispatch:  # Добавляем возможность ручного запуска

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Восстанавливаем кэш, если workflow вызван через workflow_call
      - name: Restore dependencies
        if: github.event_name == 'workflow_call'
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        
      # Устанавливаем зависимости только если workflow запущен напрямую
      - name: Set up Node.js
        if: github.event_name != 'workflow_call'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        if: github.event_name != 'workflow_call'
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile

      - name: Scrape changanauto.ru
        run: pnpm run scrape-changan

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --exit-code; then
            echo "changes=true" >> $GITHUB_ENV
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "script_output=$(echo -n 'Update Changan cars data' | base64)" >> $GITHUB_OUTPUT
          elif git status -s; then
            echo "changes=true" >> $GITHUB_ENV
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "script_output=$(echo -n 'Update Changan cars data' | base64)" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_ENV
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "script_output=$(echo -n '' | base64)" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      # Коммитим изменения только если workflow запущен напрямую
      - name: Commit files
        if: |
          env.changes == 'true' && 
          github.event_name != 'workflow_call'
        run: |
          git config --local user.email "support+actions@github.com"
          git config --local user.name "github-actions-bot"
          if [[ $(find ./src -type f -name "*.json") ]]; then git add $(find ./src -type f -name "*.json"); fi
          git commit -m "Update Changan cars data" -a || echo "No changes to commit"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin $GITHUB_REF_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      changes: ${{ steps.check_changes.outputs.changes }}
      script_output: ${{ steps.check_changes.outputs.script_output }}

  notify_telegram:
    needs: scrape
    if: |
      needs.scrape.outputs.script_output != '' && 
      github.event_name != 'workflow_call'
    uses: ./.github/workflows/github-telegram.yml
    with:
      additional-text: |
        ${{ needs.scrape.outputs.script_output }}
    secrets:
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}