name: Scrape Geely Data

on:
  push:
    paths:
      - '.github/scripts/scrape.js'
  workflow_call:
    outputs:
      changes:
        description: "Whether there were changes in the data"
        value: ${{ jobs.scrape.outputs.changes }}
      script_output:
        description: "Output message for notifications"
        value: ${{ jobs.scrape.outputs.script_output }}
  workflow_dispatch:  # Добавляем возможность ручного запуска

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile

      - name: Scrape dealer price belgee-samara.ru
        run: node .github/scripts/getDealerData.js
        env:
          CSV_URL: ${{ secrets.CSV_ALPHA }}
          QUERY_STRING: "SELECT C, D, E, F WHERE A='ЦнМ' and B='Belgee'"
          KEY_COLUMN: "Модель"
          OUTPUT_PATHS: "./src/belgee-samara.ru/data/dealer_price.json"

      - name: Scrape belgee.ru
        run: node .github/scripts/scrape.js
        env:
          BRAND: "belgee"
          URL: "https://belgee.ru"
          ITEM_XPATH: "//header/div[@data-id='models']/div"
          ID_XPATH: "concat('belgee-', substring-after(substring-after(./a/@href, '/model/'), 'belgee-'))"
          MODEL_XPATH: "./a/span[@class='title']/text()"
          PRICE_XPATH: "translate(string(./a/span[@class='subtitle']/text()), translate(string(./a/span[@class='subtitle']/text()), '0123456789', ''), '')"
          LINK_XPATH: "./a/@href"
          OUTPUT_PATHS: "./src/belgee-orenburg.ru/data/cars.json,./src/belgee-smr.ru/data/cars.json,./src/belgee-partner-saratov.ru/data/cars.json,./src/belgee-samara.ru/data/cars.json,./tmp/auto-team.pro/data/belgee.json"
          DEALERPRICE: 'dealer_price.json'
          DEALERPRICEFIELD: 'Конечная цена'
          DEALERBENEFITFIELD: 'Скидка'

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --exit-code; then
            echo "changes=true" >> $GITHUB_ENV
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "script_output=$(echo -n 'Update Geely cars data' | base64)" >> $GITHUB_OUTPUT
          elif git status -s; then
            echo "changes=true" >> $GITHUB_ENV
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "script_output=$(echo -n 'Update Geely cars data' | base64)" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_ENV
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "script_output=$(echo -n '' | base64)" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Commit files
        if: |
          env.changes == 'true' && 
          github.event_name != 'workflow_call'  # Не делаем коммит если вызван из основного workflow
        run: |
          git config --local user.email "support+actions@github.com"
          git config --local user.name "github-actions-bot"
          if [[ $(find ./src -type f -name "*.json") ]]; then git add $(find ./src -type f -name "*.json"); fi
          git commit -m "Update Geely cars data" -a || echo "No changes to commit"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin $GITHUB_REF_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      changes: ${{ steps.check_changes.outputs.changes }}
      script_output: ${{ steps.check_changes.outputs.script_output }}

  notify_telegram:
    needs: scrape
    if: |
      needs.scrape.outputs.script_output != '' && 
      github.event_name != 'workflow_call'  # Не отправляем уведомление если вызван из основного workflow
    uses: ./.github/workflows/github-telegram.yml
    with:
      additional-text: |
        ${{ needs.scrape.outputs.script_output }}
    secrets:
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}